/**
 * Logo for each technology named on the site, from svgl.app (dark variants).
 * Files live in public/icons. A name with no entry is shown as text.
 */
export const TECH_ICONS: Record<string, string> = {
  "TypeScript": "typescript.svg",
  "Typescript": "typescript.svg",
  "JavaScript": "javascript.svg",
  "React": "react.svg",
  "React Native": "react.svg",
  "Next.js": "next-js.svg",
  "TanStack Query": "react-query.svg",
  "Redux": "redux.svg",
  "Tailwind": "tailwind-css.svg",
  "TailwindCSS": "tailwind-css.svg",
  "Tailwind + ShadCN": "tailwind-css.svg",
  "Shadcn UI": "shadcn-ui.svg",
  "Storybook": "storybook.svg",
  "Remix": "remix.svg",
  "Node": "node-js.svg",
  "Node.js": "node-js.svg",
  "Nest.js": "nestjs.svg",
  "Bun": "bun.svg",
  "Deno": "deno.svg",
  "Spring Boot": "spring.svg",
  "FastAPI": "fastapi.svg",
  "Fast API": "fastapi.svg",
  "Kafka": "apache-kafka.svg",
  "Prisma": "prisma.svg",
  "TypeORM": "typeorm.svg",
  "Socket.io": "socket-io.svg",
  "Python": "python.svg",
  "PostgreSQL": "postgresql.svg",
  "MySQL": "mysql.svg",
  "MS SQL": "microsoft-sql-server.svg",
  "MongoDB": "mongodb.svg",
  "Redis": "redis.svg",
  "Firebase": "firebase.svg",
  "Firestore": "firebase.svg",
  "FCM": "firebase.svg",
  "Supabase": "supabase.svg",
  "Convex": "convex.svg",
  "Azure": "microsoft-azure.svg",
  "Azure DevOps": "microsoft-azure.svg",
  "Vercel": "vercel.svg",
  "Docker": "docker.svg",
  "GitHub Actions": "github.svg",
  "Bash": "bash.svg",
  "Datadog": "datadog.svg",
  "Sentry": "sentry.svg",
  "AWS": "amazon-web-services.svg",
  "AWS S3": "amazon-web-services.svg",
  "GCP": "google.svg",
  "Claude": "claude-ai.svg",
  "Vercel AI SDK": "vercel.svg",
  "LangChain": "langchain.svg",
  "Langchain": "langchain.svg",
  "LangGraph": "langchain.svg",
  "MCP": "model-context-protocol.svg",
  "TensorFlow": "tensorflow.svg",
  "Gemini 2.5 Pro": "gemini.svg",
  "Gemini 2.5 Flash": "gemini.svg",
  "Gemini 2.5 Flash + 2.5 Pro": "gemini.svg",
  "GPT-4o": "openai.svg",
  "Azure OpenAI": "openai.svg",
  "Jest": "jest.svg",
  "Playwright": "playwright.svg",
  "Flutter": "flutter.svg",
  "Android": "android.svg",
  "iOS": "apple.svg",
  "JSON": "json.svg",
  "GitHub": "github.svg",
  "LinkedIn": "linkedin.svg",
  "X": "x-formerly-twitter.svg",
};

/** Logos whose brand colour is too dark for the site's background; drawn in white instead. */
export const LIGHTEN_ICONS = new Set(["datadog.svg", "sentry.svg"]);
